### ISSUE TITLE
[UI]  Main text box for describing objects at bottom of UI

### ISSUE THREAD

**Issue by Jared-Sprague** [CommandLineHeroes/hero-engine#16]
When looking at an object by left clicking it,  a description of that object should show up in a UI text box at the bottom of the screen.   See the example drawing:
![uitextbox](https://user-images.githubusercontent.com/3926730/46288856-3a8cd400-c555-11e8-8730-090c28f0e791.png)

You can use the object_selection example as a starting point, just make a copy of hero-engine/examples/reference_room/object_selection/  and call it main_text,  then write code to popup the text box when you click on the window.

**Comment by JeffreyBrettColeman** [comment]
Noted. Will take a look when I'm free. Looks like a fun foray into WebGL.

**Comment by LiquidityC** [comment]
Is there anything left to do in this issue? I checked out the merged PR and that solution seems pretty solid.

I had a patch set going but as I was working on two machines, 1080p desktop and a HiDPI laptop. I got issues with positioning on the higher resolution, I've yet to test the merged PR on this laptop though. Might be that I just had some bad code in my solution.

**Comment by Jared-Sprague** [comment]
I think this is good for now.  We'll need to enhance it in the future to allow style customization, changing font, background color etc per game.  But we can open a separate issue for that.
