### ISSUE TITLE
[Reference Room] Click to walk

### ISSUE THREAD

**Issue by Jared-Sprague** [CommandLineHeroes/hero-engine#3]
Left click the mouse in the scene to move the character sprite to that position.

**Comment by nwforrer** [comment]
I can work on this. Should the movement be restricted to left and right, or can the player move to any floor space in a room if it has some "depth" to it?

**Comment by Jared-Sprague** [comment]
@nwforrer someone from [discord](https://discord.gg/rpnmpVj) said they were going to work on this over the weekend, so I would hold off.   If after the weekend no one has done it than go for it.

@nwforrer I think #6  would be a great one for you if you're interested since you did the click objects example and this is a good continuation of that.
