### ISSUE TITLE
[Reference Room]  Activate an object and chain action

### ISSUE THREAD

**Issue by Jared-Sprague** [CommandLineHeroes/hero-engine#6]
Activate an object that can also trigger another action on another object.   For example pull a lever that opens a door.   Or flip a light switch that turns on/off the lights.

**Comment by Jared-Sprague** [comment]
This should get the properties for the event from Tiled.

For example in tiled there would be two objects.
name=light_switch
name=celing_light

In the light_switch object it would have a custom property that looks like this:
![screenshot from 2018-09-15 22-26-27](https://user-images.githubusercontent.com/3926730/45592294-1915d080-b937-11e8-8295-a7c663cb4c29.png)

Then in code when light_switch gets clicked it would look at the onUse property and run a command interpreter  to execute this little command with it's args.  For this story this can just be **HARD CODED** the actual interpreter will be another issue that is out of scope for this simple example.

**Comment by nwforrer** [comment]
I'll work on this one.

**Comment by Jared-Sprague** [comment]
@nwforrer  Love the work you did on this thanks!  Hey are you on our discord server?  https://discord.gg/rpnmpVj

**Comment by nwforrer** [comment]
@Jared-Sprague thanks! Yes, my discord nickname is nicksmaddog.
